sonar.projectKey=student-management-system
sonar.projectName=Student Management System

sonar.sources=admin,student,config,python,index.php

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/vendor/**,**/__pycache__/**,k8s/**,argocd/**
