apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-pvc
  namespace: student-management

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3    

  resources:
    requests:
      storage: 5Gi
