apiVersion: v1
kind: Service

metadata:
  name: student-management-php
  namespace: student-management

spec:
  selector:
    app: student-management-php

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer
