apiVersion: v1
kind: Service

metadata:
  name: student-management-python
  namespace: student-management

spec:
  selector:
    app: student-management-python

  ports:
    - port: 5000
      targetPort: 5000

  type: ClusterIP
